db.url=jdbc:postgresql://localhost:5432/hospital_management_test
db.username=postgres
db.password=12346
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
