spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_management_test
spring.datasource.username=anishraj
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
