import com.hospital.dto.AppointmentDTO;
import com.hospital.dto.DoctorDTO;
import com.hospital.dto.HospitalDTO;
import com.hospital.entity.Appointment;
import com.hospital.entity.Doctor;
import com.hospital.entity.Hospital;

import java.time.LocalDateTime;
public class Main {
    public static void main(String[] args) {
        System.out.println("=== Hospital Management Demo ===");

        // 1. Create a Hospital using Lombok Builder
        Hospital hospital = Hospital.builder()
                .id(1L)
                .name("General City Hospital")
                .address("123 Health Ave, Metro City")
                .phone("555-0199")
                .build();

        // 2. Create Doctors using Lombok Builder and associate with Hospital
        Doctor doctor1 = Doctor.builder()
                .id(101L)
                .name("Dr. Alice Smith")
                .specialty("Cardiology")
                .phone("555-0121")
                .build();
        doctor1.setHospital(hospital);

        Doctor doctor2 = Doctor.builder()
                .id(102L)
                .name("Dr. Bob Jones")
                .specialty("Pediatrics")
                .phone("555-0122")
                .build();
        doctor2.setHospital(hospital);

        // 3. Create an Appointment and associate with a Doctor
        Appointment appointment = Appointment.builder()
                .id(1001L)
                .patientName("John Doe")
                .patientPhone("555-9876")
                .appointmentTime(LocalDateTime.of(2026, 6, 25, 10, 30))
                .status("SCHEDULED")
                .build();
        appointment.setDoctor(doctor1);

        // Print entities (using @ToString generated by Lombok, with exclusions configured to prevent circular references)
        System.out.println("\n--- Entity Instances ---");
        System.out.println(hospital);
        System.out.println(doctor1);
        System.out.println(doctor2);
        System.out.println(appointment);

        // 4. Map entities to Java 21 Records (DTOs)
        HospitalDTO hospitalDTO = HospitalDTO.fromEntity(hospital);
        DoctorDTO doctorDTO = DoctorDTO.fromEntity(doctor1);
        AppointmentDTO appointmentDTO = AppointmentDTO.fromEntity(appointment);

        // Print DTOs (using built-in record toString methods)
        System.out.println("\n--- DTO (Java Records) Mapped From Entities ---");
        System.out.println(hospitalDTO);
        System.out.println(doctorDTO);
        System.out.println(appointmentDTO);

        System.out.println("\nDemo completed successfully!");
    }
}
